---
description: 'Дополнительные сведения: оператор "Throw" не может опускать операнд вне оператора "Catch" или внутри оператора "finally"'
title: В операторе Throw запрещается опускать операнд вне оператора Catch и в операторе Finally
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: 8ab76ae9e5727388ddb77ec38f1b4e89b6a0e5d6
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 02/14/2021
ms.locfileid: "100460843"
---
# <a name="throw-statement-cannot-omit-operand-outside-a-catch-statement-or-inside-a-finally-statement"></a><span data-ttu-id="01d34-103">В операторе Throw запрещается опускать операнд вне оператора Catch и в операторе Finally</span><span class="sxs-lookup"><span data-stu-id="01d34-103">'Throw' statement cannot omit operand outside a 'Catch' statement or inside a 'Finally' statement</span></span>

<span data-ttu-id="01d34-104">В операторах`Throw` , находящихся вне оператора `Catch` , должно быть указано имя объекта исключения.</span><span class="sxs-lookup"><span data-stu-id="01d34-104">`Throw` statements outside of `Catch` statement must supply the name of an exception object.</span></span>  
  
 <span data-ttu-id="01d34-105">**Идентификатор ошибки:** BC30666</span><span class="sxs-lookup"><span data-stu-id="01d34-105">**Error ID:** BC30666</span></span>  
  
## <a name="to-correct-this-error"></a><span data-ttu-id="01d34-106">Исправление ошибки</span><span class="sxs-lookup"><span data-stu-id="01d34-106">To correct this error</span></span>  
  
1. <span data-ttu-id="01d34-107">Укажите имя объекта исключения, производного от класса `System.Exception`.</span><span class="sxs-lookup"><span data-stu-id="01d34-107">Specify the name of an exception object derived from `System.Exception`.</span></span>  
  
2. <span data-ttu-id="01d34-108">Измените структуру кода таким образом, чтобы оператор `Throw` находился внутри блока `Catch` .</span><span class="sxs-lookup"><span data-stu-id="01d34-108">Restructure your code so that the `Throw` statement is inside a `Catch` block.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="01d34-109">См. также раздел</span><span class="sxs-lookup"><span data-stu-id="01d34-109">See also</span></span>

- [<span data-ttu-id="01d34-110">Оператор Throw</span><span class="sxs-lookup"><span data-stu-id="01d34-110">Throw Statement</span></span>](../language-reference/statements/throw-statement.md)
- [<span data-ttu-id="01d34-111">Оператор Try...Catch...Finally</span><span class="sxs-lookup"><span data-stu-id="01d34-111">Try...Catch...Finally Statement</span></span>](../language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [<span data-ttu-id="01d34-112">Обработка и создание исключений в .NET</span><span class="sxs-lookup"><span data-stu-id="01d34-112">Handling and throwing exceptions in .NET</span></span>](../../standard/exceptions/index.md)
